### ISSUE TITLE
NanoDJ Vice app in CyVerse

### ISSUE THREAD

**Issue by upendrak** [genomicsITER/NanoDJ#2]
Firstly, we appreciate your effort in building NanoDJ and it's an excellent tool for minION data analysis. I have recently built a NanoDJ app in CyVerse Discovery Environment. Here is the link to the [quick launch] (https://cyverse-nanodj.readthedocs-hosted.com/en/latest/) of NanoDJ in CyVerse Discovery Environment.

If you like, you can put the VICE button on your GitHub for people to easily launch NanoDJ for your users. More details are [here](https://cyverse-nanodj.readthedocs-hosted.com/en/latest/)

P.s. I tried to launch the binder and run NanoDJ but it always fails for me. Can you please take a look at it?

**Comment by genomicsITER** [comment]
Hi @upendrak. Thank for your support!

As you can see, the VICE button is now included in the README and also some information about the Cyverse project. We have solved the Binder issue and now the container build is successful and the educational notebook can be accesesed
